name: ${project.name}
version: '${minecraft.plugin.version}'
main: de.minebench.plotgenerator.PlotGenerator
depend: [WorldEdit]
softdepend: [MbRegionConomy,WorldGuard]
authors: [Phoenix616]
description: ${project.description}